spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /api

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: mauricio
    password: admin123
server:
  port: 8090

---
spring:
  profiles: prod
server:
  port: 80
