services:
  mysql:
    image: mysql:5
    container_name: mysql
    environment:
      - MYSQL_DATABASE=foundation
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/libs/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MY_SQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80
    depends_on:
      - mysql